### ISSUE TITLE
Have better explanations for settings

### ISSUE THREAD

**Issue by Erimelowo** [Erimelowo/OpenVR-Dynamic-Resolution#13]
Values ranges (e.g. resolution is 20 to 500)
More through explanations?
Examples (If you want x, do y)

**Comment by Crimson-foxGITHUB** [comment]
resIncreaseThreshold and resDecreaseThreshold: think of this as a buffer between your frametimes and actual hardware consumption

**Comment by Louka3000** [comment]
Hardware consumption?

**Comment by Crimson-foxGITHUB** [comment]
> Hardware consumption?

how much of the GPU is being used

**Comment by Louka3000** [comment]
Still doesn't make sense, that's not what the setting does...

**Comment by Erimelowo** [comment]
Working on this in https://github.com/Erimelowo/OpenVR-Dynamic-Resolution/tree/imgui
