### ISSUE TITLE
EnabledApps Feature

### ISSUE THREAD

**Issue by uhCrow** [Erimelowo/OpenVR-Dynamic-Resolution#32]
Adding a feature where it would only be enabled with the listed apps e.g vrchat only and pause during everything else or set list.

It would be helpful instead of going one by one grabbing steam app ids.

**Comment by Erimelowo** [comment]
Good idea, shouldn’t be hard to implement

**Comment by Erimelowo** [comment]
Didn't implement this yet, but [v1.0.0](https://github.com/Erimelowo/OpenVR-Dynamic-Resolution/releases/tag/v1.0.0) has a button to add the current running application to the list of disabled application, as well as a button to temporarily pause resolution adjustment.

**Comment by Erimelowo** [comment]
Implemented in https://github.com/Erimelowo/OpenVR-Dynamic-Resolution/commit/d5889d48d47dff088f60ed6b3b636e42d9c38626 and soon available in v1.2.0
