### ISSUE TITLE
Target FPS feature suggestion

### ISSUE THREAD

**Issue by WebserferOwO** [Erimelowo/OpenVR-Dynamic-Resolution#39]
(Hope this is the correct place for this)
So I just got this app from steam and had a suggestion for customizing the target fps. Unless I'm missing the feature if it exists, it'd be nice to tell the app to not change resolution until it goes below a certain frame rate.

My normal target FPS is 72fps, but I can handle say 40-30fps, so would rather it keep full resolution until it's below that.
If that is a feature that's my bad but I couldn't seem to find it, I thought increase/decrease threshold but it didn't seem to do what I'd needed.

Either way great app, amazed it took this long for someone to make an app for this feature, great job :D

**Comment by Erimelowo** [comment]
The thresholds would what you would use to target any frametime (which you can easily translate into FPS) (set them to like 160% and 176% for double frametime/half FPS).

 You can also simply enable “Always reproject” (without touching the thresholds) to target half the FPS directly which was actually made for your use case ^^.

**Comment by WebserferOwO** [comment]
> The thresholds would what you would use to target any frametime (which you can easily translate into FPS) (set them to like 160% and 176% for double frametime/half FPS).
> 
> You can also simply enable “Always reproject” (without touching the thresholds) to target half the FPS directly which was actually made for your use case ^^.

It seem I can't set increase/decrease threshold above 100% in the app, and enabling "Always reproject” doesn't seem to have any effect, the resolution still drops really low even when being above half my target fps.

**Comment by Erimelowo** [comment]
The thresholds are indeed  limited to 100% max in GUI my bad, I just removed this limitation and it will be fixed in the next version.

As for Always reproject, it shouldn’t let you go above 36 FPS in your case (it will start increasing resolution if above 36 and decrease it if below). What app/game are you testing this on?
