### ISSUE TITLE
[Feature Request] Target Frametime Offset

### ISSUE THREAD

**Issue by LIII-Works** [Erimelowo/OpenVR-Dynamic-Resolution#42]
**Description**:  
Currently, the frametime is automatically calculated based on the HMD refresh rate (either 1x or 1/2). This feature would allow users to specify an offset to the target frametime. The offset would create a small buffer, or headroom, to account for unstable frametime. This would provide enough time for OVR DR to respond before the frametime exceeds the target.

**Benefits**:
- Gives OVR DR enough time to react before the frametime breaks through the target limit.
- Enhances performance in reprojection where frametime stability is critical.

**Suggested Implementation**:
- Add a text box in the settings where users can input the desired target frametime offset (positive or negative value).

**Comment by Erimelowo** [comment]
Isn’t this just the resIncreaseThreshold and resDecreaseThreshold?
